In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\ankit\anaconda3\lib\site-packages (1.0.5)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\ankit\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\ankit\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\ankit\anaconda3\lib\site-packages (from pandas) (1.18.5)
Requirement already satisfied: six>=1.5 in c:\users\ankit\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_csv('Cleaned-Data.csv')

In [4]:
df.tail()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country
316795,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,Other
316796,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,1,0,0,Other
316797,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,0,1,Other
316798,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,1,0,Other
316799,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,1,0,0,Other

In [5]:
df.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country
0,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,0,1,China
1,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,1,0,China
2,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,1,0,0,China
3,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,0,1,China
4,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,1,0,China

In [6]:
df.shape

(316800, 27)

In [7]:
df.dtypes

Fever                       int64
Tiredness                   int64
Dry-Cough                   int64
Difficulty-in-Breathing     int64
Sore-Throat                 int64
None_Sympton                int64
Pains                       int64
Nasal-Congestion            int64
Runny-Nose                  int64
Diarrhea                    int64
None_Experiencing           int64
Age_0-9                     int64
Age_10-19                   int64
Age_20-24                   int64
Age_25-59                   int64
Age_60+                     int64
Gender_Female               int64
Gender_Male                 int64
Gender_Transgender          int64
Severity_Mild               int64
Severity_Moderate           int64
Severity_None               int64
Severity_Severe             int64
Contact_Dont-Know           int64
Contact_No                  int64
Contact_Yes                 int64
Country                    object
dtype: object

In [8]:
df['Severity'] = (df.iloc[:, 19:23] == 1).idxmax(1)

In [9]:
df.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Severity
0,1,1,1,1,1,0,1,1,1,1,...,0,1,0,0,0,0,0,1,China,Severity_Mild
1,1,1,1,1,1,0,1,1,1,1,...,0,1,0,0,0,0,1,0,China,Severity_Mild
2,1,1,1,1,1,0,1,1,1,1,...,0,1,0,0,0,1,0,0,China,Severity_Mild
3,1,1,1,1,1,0,1,1,1,1,...,0,0,1,0,0,0,0,1,China,Severity_Moderate
4,1,1,1,1,1,0,1,1,1,1,...,0,0,1,0,0,0,1,0,China,Severity_Moderate

In [10]:
df['Severity'].value_counts()

Severity_Severe      79200
Severity_Mild        79200
Severity_Moderate    79200
Severity_None        79200
Name: Severity, dtype: int64

In [11]:
df['Target'] = df['Severity'].replace('Severity_None', 0).replace('Severity_Mild', 1).replace('Severity_Moderate', 1).replace('Severity_Severe', 1)

In [12]:
df.tail()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Severity,Target
316795,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,1,0,Other,Severity_Severe,1
316796,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,Other,Severity_Severe,1
316797,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,Other,Severity_None,0
316798,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,1,0,Other,Severity_None,0
316799,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,1,0,0,Other,Severity_None,0

In [13]:
df.iloc[:, 23:26].head()

   Contact_Dont-Know  Contact_No  Contact_Yes
0                  0           0            1
1                  0           1            0
2                  1           0            0
3                  0           0            1
4                  0           1            0

In [14]:
df['Contact'] = (df.iloc[:, 23:26] == 1).idxmax(1)

In [15]:
df.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Severity,Target,Contact
0,1,1,1,1,1,0,1,1,1,1,...,0,0,0,0,0,1,China,Severity_Mild,1,Contact_Yes
1,1,1,1,1,1,0,1,1,1,1,...,0,0,0,0,1,0,China,Severity_Mild,1,Contact_No
2,1,1,1,1,1,0,1,1,1,1,...,0,0,0,1,0,0,China,Severity_Mild,1,Contact_Dont-Know
3,1,1,1,1,1,0,1,1,1,1,...,1,0,0,0,0,1,China,Severity_Moderate,1,Contact_Yes
4,1,1,1,1,1,0,1,1,1,1,...,1,0,0,0,1,0,China,Severity_Moderate,1,Contact_No

In [16]:
df['Contact'].value_counts()

Contact_Dont-Know    105600
Contact_No           105600
Contact_Yes          105600
Name: Contact, dtype: int64

In [17]:
df['Contact'] = df['Contact'].replace('Contact_No', 0).replace('Contact_Yes', 1).replace('Contact_Dont-Know', 2)

In [18]:
df.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Severity,Target,Contact
0,1,1,1,1,1,0,1,1,1,1,...,0,0,0,0,0,1,China,Severity_Mild,1,1
1,1,1,1,1,1,0,1,1,1,1,...,0,0,0,0,1,0,China,Severity_Mild,1,0
2,1,1,1,1,1,0,1,1,1,1,...,0,0,0,1,0,0,China,Severity_Mild,1,2
3,1,1,1,1,1,0,1,1,1,1,...,1,0,0,0,0,1,China,Severity_Moderate,1,1
4,1,1,1,1,1,0,1,1,1,1,...,1,0,0,0,1,0,China,Severity_Moderate,1,0

In [19]:
df.dtypes

Fever                       int64
Tiredness                   int64
Dry-Cough                   int64
Difficulty-in-Breathing     int64
Sore-Throat                 int64
None_Sympton                int64
Pains                       int64
Nasal-Congestion            int64
Runny-Nose                  int64
Diarrhea                    int64
None_Experiencing           int64
Age_0-9                     int64
Age_10-19                   int64
Age_20-24                   int64
Age_25-59                   int64
Age_60+                     int64
Gender_Female               int64
Gender_Male                 int64
Gender_Transgender          int64
Severity_Mild               int64
Severity_Moderate           int64
Severity_None               int64
Severity_Severe             int64
Contact_Dont-Know           int64
Contact_No                  int64
Contact_Yes                 int64
Country                    object
Severity                   object
Target                      int64
Contact                     int64
dtype: object

In [20]:
df.iloc[:, 11:16].head()

   Age_0-9  Age_10-19  Age_20-24  Age_25-59  Age_60+
0        1          0          0          0        0
1        1          0          0          0        0
2        1          0          0          0        0
3        1          0          0          0        0
4        1          0          0          0        0

In [21]:
df['Age_Label'] = (df.iloc[:, 11:16] == 1).idxmax(1)
df['Age_Label'] = df['Age_Label'].replace('Age_0-9', 0).replace('Age_10-19', 1).replace('Age_20-24', 2).replace('Age_25-59', 3).replace('Age_60+', 4)

In [22]:
df.tail()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Severity,Target,Contact,Age_Label
316795,0,0,0,0,0,1,0,0,0,0,...,0,1,0,1,0,Other,Severity_Severe,1,0,4
316796,0,0,0,0,0,1,0,0,0,0,...,0,1,1,0,0,Other,Severity_Severe,1,2,4
316797,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,1,Other,Severity_None,0,1,4
316798,0,0,0,0,0,1,0,0,0,0,...,1,0,0,1,0,Other,Severity_None,0,0,4
316799,0,0,0,0,0,1,0,0,0,0,...,1,0,1,0,0,Other,Severity_None,0,2,4

In [23]:
df.iloc[:, 16:19].head()

   Gender_Female  Gender_Male  Gender_Transgender
0              0            1                   0
1              0            1                   0
2              0            1                   0
3              0            1                   0
4              0            1                   0

In [24]:
df['Gender'] = (df.iloc[:, 16:19] == 1).idxmax(1)
df['Gender'] = df['Gender'].replace('Gender_Female', 1).replace('Gender_Male', 0).replace('Gender_Transgender', 2)

In [25]:
df.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Severity,Target,Contact,Age_Label,Gender
0,1,1,1,1,1,0,1,1,1,1,...,0,0,0,1,China,Severity_Mild,1,1,0,0
1,1,1,1,1,1,0,1,1,1,1,...,0,0,1,0,China,Severity_Mild,1,0,0,0
2,1,1,1,1,1,0,1,1,1,1,...,0,1,0,0,China,Severity_Mild,1,2,0,0
3,1,1,1,1,1,0,1,1,1,1,...,0,0,0,1,China,Severity_Moderate,1,1,0,0
4,1,1,1,1,1,0,1,1,1,1,...,0,0,1,0,China,Severity_Moderate,1,0,0,0

In [26]:
df['Diarrhea'].value_counts()

0    201600
1    115200
Name: Diarrhea, dtype: int64

In [27]:
df.columns

Index(['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing',
       'Sore-Throat', 'None_Sympton', 'Pains', 'Nasal-Congestion',
       'Runny-Nose', 'Diarrhea', 'None_Experiencing', 'Age_0-9', 'Age_10-19',
       'Age_20-24', 'Age_25-59', 'Age_60+', 'Gender_Female', 'Gender_Male',
       'Gender_Transgender', 'Severity_Mild', 'Severity_Moderate',
       'Severity_None', 'Severity_Severe', 'Contact_Dont-Know', 'Contact_No',
       'Contact_Yes', 'Country', 'Severity', 'Target', 'Contact', 'Age_Label',
       'Gender'],
      dtype='object')

In [28]:
X = df[['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing',
       'Sore-Throat', 'Pains', 'Nasal-Congestion',
       'Runny-Nose', 'Diarrhea', 'Contact', 'Age_Label',
       'Gender']]
X.head(30)

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,Contact,Age_Label,Gender
0,1,1,1,1,1,1,1,1,1,1,0,0
1,1,1,1,1,1,1,1,1,1,0,0,0
2,1,1,1,1,1,1,1,1,1,2,0,0
3,1,1,1,1,1,1,1,1,1,1,0,0
4,1,1,1,1,1,1,1,1,1,0,0,0
5,1,1,1,1,1,1,1,1,1,2,0,0
6,1,1,1,1,1,1,1,1,1,1,0,0
7,1,1,1,1,1,1,1,1,1,0,0,0
8,1,1,1,1,1,1,1,1,1,2,0,0
9,1,1,1,1,1,1,1,1,1,1,0,0
10,1,1,1,1,1,1,1,1,1,0,0,0
11,1,1,1,1,1,1,1,1,1,2,0,0
12,1,1,1,1,1,1,1,1,0,1,0,0
13,1,1,1,1,1,1,1,1,0,0,0,0
14,1,1,1,1,1,1,1,1,0,2,0,0
15,1,1,1,1,1,1,1,1,0,1,0,0
16,1,1,1,1,1,1,1,1,0,0,0,0
17,1,1,1,1,1,1,1,1,0,2,0,0
18,1,1,1,1,1,1,1,1,0,1,0,0
19,1,1,1,1,1,1,1,1,0,0,0,0
20,1,1,1,1,1,1,1,1,0,2,0,0
21,1,1,1,1,1,1,1,1,0,1,0,0
22,1,1,1,1,1,1,1,1,0,0,0,0
23,1,1,1,1,1,1,1,1,0,2,0,0
24,1,1,1,1,1,1,1,0,0,1,0,0
25,1,1,1,1,1,1,1,0,0,0,0,0
26,1,1,1,1,1,1,1,0,0,2,0,0
27,1,1,1,1,1,1,1,0,0,1,0,0
28,1,1,1,1,1,1,1,0,0,0,0,0
29,1,1,1,1,1,1,1,0,0,2,0,0

In [29]:
Y = df[['Target']]
Y.head()

   Target
0       1
1       1
2       1
3       1
4       1

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)
x_train.shape, y_train.shape

((253440, 12), (253440, 1))

In [31]:
y_train['Target'].value_counts()

1    189997
0     63443
Name: Target, dtype: int64

In [32]:
y_test['Target'].value_counts()

1    47603
0    15757
Name: Target, dtype: int64

In [33]:
pip install sklearn

Collecting sklearn
  Using cached sklearn-0.0.tar.gz (1.1 kB)
Requirement already satisfied: scikit-learn in c:\users\ankit\anaconda3\lib\site-packages (from sklearn) (0.23.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ankit\anaconda3\lib\site-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied: numpy>=1.13.3 in c:\users\ankit\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.18.5)
Requirement already satisfied: scipy>=0.19.1 in c:\users\ankit\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.5.0)
Requirement already satisfied: joblib>=0.11 in c:\users\ankit\anaconda3\lib\site-packages (from scikit-learn->sklearn) (0.16.0)
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py): started
  Building wheel for sklearn (setup.py): finished with status 'done'
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1320 sha256=b3eca82f613c5db88f653fd02c7dbcbfb059a3486ae33eaf569ad7952c038594
  Stored in directory: c:\users\ankit\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn
Installing collected packages: sklearn
Successfully installed sklearn-0.0
Note: you may need to restart the kernel to use updated packages.

In [34]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
rf_cv = RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=5,random_state=0,cv=3,verbose=True,n_jobs=-1)
rf_cv.fit(x_train,y_train.values.ravel())

Fitting 3 folds for each of 5 candidates, totalling 15 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.

In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(x_train, y_train.values.ravel())

In [ ]:
y_pred = LR.predict(x_test)

In [ ]:
from sklearn.metrics import f1_score, accuracy_score

In [ ]:
f1_score(y_test, y_pred, average='weighted')

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [ ]:
classifier  = Sequential()
classifier.add(Dense(input_dim=12,units=16,activation='relu',kernel_initializer='he_normal'))
classifier.add(Dense(units=16,activation='relu',kernel_initializer='he_uniform'))
classifier.add(Dense(units=32,activation='relu',kernel_initializer='he_uniform'))
classifier.add(Dropout(0.4))
classifier.add(Dense(units=32,activation='relu',kernel_initializer='he_uniform'))
classifier.add(Dropout(0.4))
classifier.add(Dense(units=64,activation='relu',kernel_initializer='he_uniform'))
classifier.add(Dropout(0.4))
classifier.add(Dense(units=128,activation='relu',kernel_initializer='he_uniform'))
classifier.add(Dropout(0.4))
classifier.add(Dense(units=1,activation='sigmoid',kernel_initializer='uniform'))

In [ ]:
classifier.summary()

In [ ]:
classifier.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
classifier.fit(x_train,y_train.values.ravel(),epochs=20,validation_split=0.2,verbose=2)

In [ ]:
y_pred = classifier.predict(x_test)
y_pred=y_pred>0.5
from sklearn.metrics import f1_score, accuracy_score
accuracy_score(y_test, y_pred)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train, y_train.values.ravel())

In [ ]:
y_pred = rf.predict(x_test)
from sklearn.metrics import f1_score, accuracy_score
accuracy_score(y_test, y_pred)